In [1]:
from dis import dis
# from tkinter.tix import AUTO
from requests import head
import torch
import config
import os
from glob import glob
from shutil import copyfile
import pandas as pd
import re
import numpy as np
from math import sqrt
import math
import tensorflow as tf
from keras import regularizers
from tensorflow.keras import Model, Sequential
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.losses import MeanSquaredLogarithmicError
from sklearn.ensemble import ExtraTreesClassifier
import matplotlib.pyplot as plt
from re import X
import numpy as np
import torch
import pandas as pd
from torch.nn.utils.rnn import pack_padded_sequence
from torch.utils.data import DataLoader
from CustomDataset import CustomRawDataset
from model_dispatcher import dispatch_model
from tensorflow import keras
# from model_dispatcher_cnn import dispatch_model
import config
from torch import nn
import os
from glob import glob
from torch.optim import Adam, SGD
from torch.optim.lr_scheduler import ReduceLROnPlateau
from datetime import date, timedelta, datetime
import time
import random
from torch.utils.tensorboard import SummaryWriter
from CustomDataset import custom_collate_fn
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report, confusion_matrix

import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation,TimeDistributed
from tensorflow.keras.layers import Bidirectional, GlobalMaxPool1D
from tensorflow.keras.models import Model, Sequential
from tensorflow.compat.v1.keras.layers import CuDNNLSTM
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [188]:
data=pd.read_csv(r'D:\Research_Project\My_project_22\input\final_preprocessed_merged\corr_eigen_snr_20.csv')
for i in range(7,20):
    data1=data[data['target']==i]
    data1.to_csv(rf"D:\Research_Project\My_project_22\test_cases\data{i}.csv",index=False)
    

In [2]:

data=pd.read_csv(r'D:\Research_Project\My_project_22\input\final_preprocessed_merged\corr_eigen_snr_20.csv')
data1=data[data['target']==4]
data1.to_csv(rf"D:\Research_Project\My_project_22\test_cases\data{4}.csv",index=False)

data1.head()

right_knee_pitch  right_hip_roll  right_hip_pitch  left_knee_pitch  \
5030          0.121903        0.038988         0.113879         0.114846   
5031          0.119257        0.034982         0.114711         0.117124   
5032          0.120468        0.033192         0.114249         0.117947   
5033          0.122183        0.032563         0.115069         0.118177   
5034          0.122157        0.031499         0.115971         0.118488   

      left_hip_roll  left_hip_pitch  right_elbow_roll  right_elbow_yaw  \
5030       0.017557        0.150410          0.284294         1.160367   
5031       0.014563        0.150273          0.275100         1.165809   
5032       0.013959        0.149235          0.272892         1.166744   
5033       0.013525        0.149251          0.273071         1.166280   
5034       0.012535        0.149147          0.271593         1.166570   

      right_shoulder_roll  right_shoulder_pitch  left_elbow_roll  \
5030            -0.109664              1.567624        -0.315666   
5031            -0.104783              1.565648        -0.313013   
5032            -0.103607              1.565254        -0.314005   
5033            -0.103582              1.565256        -0.314829   
5034            -0.103002              1.564861        -0.314296   

      left_elbow_yaw  left_shoulder_roll  target  
5030       -0.975492            0.161936       4  
5031       -0.984261            0.159805       4  
5032       -0.983902            0.160367       4  
5033       -0.979745            0.161507       4  
5034       -0.977290            0.161714       4

In [141]:
data1.to_csv(r"D:\Research_Project\My_project_22\test_cases\data6.csv",index=False)

In [97]:
data=pd.read_csv(r'D:\Research_Project\My_project_22\test_cases\data1')
data.head()

right_knee_pitch  right_hip_roll  right_hip_pitch  left_knee_pitch  \
0          0.090965        0.035262         0.138708         0.116319   
1          0.092961        0.030097         0.123368         0.121511   
2          0.092333        0.029821         0.119242         0.124140   
3          0.092435        0.029634         0.113234         0.127447   
4          0.095592        0.029209         0.096278         0.134211   

   left_hip_roll  left_hip_pitch  right_elbow_roll  right_elbow_yaw  \
0       0.007711        0.194186          0.315663         1.300775   
1       0.015423        0.187449          0.295418         1.151723   
2       0.018301        0.185922          0.330067         1.232012   
3       0.022071        0.184876          0.320803         1.175950   
4       0.032760        0.180463          0.298554         1.082221   

   right_shoulder_roll  right_shoulder_pitch  left_elbow_roll  left_elbow_yaw  \
0            -0.099517              1.622800        -0.266469       -1.190872   
1            -0.127164              1.572661        -0.298012       -0.992965   
2            -0.129688              1.570423        -0.314947       -0.972014   
3            -0.139007              1.547141        -0.335349       -1.002297   
4            -0.154935              1.490168        -0.301416       -0.943832   

   left_shoulder_roll  target  
0            0.140021       1  
1            0.150684       1  
2            0.156054       1  
3            0.153873       1  
4            0.148528       1

In [189]:
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :13], sequences[end_ix-1, 13:]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [281]:
data=pd.read_csv(r'D:\Research_Project\My_project_22\test_cases\data19.csv')
x=data['target'].unique()[0]
data=data.drop(['target'],axis=1)
data.head()
for i in range(20):
    data[i]=0
data[x]=1


# data=pd.get_dummies(data,columns=['target'])

# # x=x[None:]
# # print(x.shape)
# # print(y.shape)
# # data=data.to_numpy()
# print(data.shape)

# y=data.iloc[:,26:]
# x=data.iloc[:,:26]
# # x=data[-1:26]
# print(x.shape)
# print(y.shape)
# x=x.to_numpy()
# y=y.to_numpy()


In [282]:
data=data.to_numpy()
x_test,y_test=split_sequences(data,6)

In [283]:
y_test

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [284]:
new_model = tf.keras.models.load_model(r'D:\Research_Project\My_project_22\models\my_model')
new_model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_8 (Conv1D)           (None, 4, 64)             2560      
                                                                 
 conv1d_9 (Conv1D)           (None, 2, 64)             12352     
                                                                 
 dropout_4 (Dropout)         (None, 2, 64)             0         
                                                                 
 max_pooling1d_4 (MaxPooling  (None, 1, 64)            0         
 1D)                                                             
                                                                 
 flatten_4 (Flatten)         (None, 64)                0         
                                                                 
 dense_8 (Dense)             (None, 100)               6500      
                                                      

In [285]:
y_pred=new_model.predict(x_test)
y_pred1=np.argmax(y_pred,axis=1)
y_test1=np.argmax(y_test,axis=1)
# print('Restored model, accuracy: {:5.2f}%'.format(100 * acc))

33/33 [==============================] - 0s 4ms/step


In [286]:
cf_matrix=metrics.confusion_matrix(y_test1,y_pred1)
print('Confusion matrix\n',cf_matrix)
print(metrics.classification_report(y_test1,y_pred1))

Confusion matrix
 [[   0    0    0    0]
 [   0    0    0    0]
 [   0    0    0    0]
 [   1    2    2 1038]]
              precision    recall  f1-score   support

           9       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         0
          17       0.00      0.00      0.00         0
          19       1.00      1.00      1.00      1043

    accuracy                           1.00      1043
   macro avg       0.25      0.25      0.25      1043
weighted avg       1.00      1.00      1.00      1043



c:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(r